runtime: custom
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5

env_variables:
  ClientBuildEnv: dev
  ServerBuildEnv: dev
# gcloud auth configure-docker asia-east1-docker.pkg.dev
# gcloud artifacts repositories list --location=asia-east1
# docker build --build-arg ClientBuildEnv=dev --build-arg ServerBuildEnv=dev -t asia-east1-docker.pkg.dev/wade-personal/golden-dream/v0.1.5 .
# docker push asia-east1-docker.pkg.dev/wade-personal/golden-dream/v0.1.5
# gcloud app deploy --verbosity=debug
# gcloud app logs tail -s default
