/**
 * 各列表搜尋欄位條件式
 */
export enum SEARCH_ACTION_TYPES {
  MEMBER_NAME = 'member_name',
  MEMBER_CARD = 'member_card',
  MOBILE = 'mobile',
  EMAIL = 'email',
  CLUSTER_ID = 'cluster_id',
  CLUSTER_NAME = 'cluster_name',
  CLUSTER_DESCRIPTION = 'cluster_description',
  COMMODITY_NAME = 'commodity_name',
  COUPON_ID = 'coupon_id',
  COUPON_NAME = 'coupon_name',
  COUPON_SEND_NAME = 'coupon_send_name',
  MOT_ID = 'mot_id',
  MOT_NAME = 'mot_name',
  MOT_DESCRIPTION = 'mot_description',
  NOTIFY_NAME = 'notify_name',
  EXPORT_ID = 'export_id',
  TRANSACTION_ID = 'transaction_id',
  POINT_NAME = 'point_name',
  DATA_YEAR = 'data_year',
  REWARD_NAME = 'reward_name',
  BRAND_NAME = 'brand_name',
  STORE_ID = 'store_id',
  STORE_NAME = 'store_name',
  MALL_NAME = 'mall_name',
  TAG_NAME = 'tag_name',
  BUSINESS_GROUP = 'business_group',
  ACCOUNT = 'account',
  POS_STORE = 'pos_store',
  PRODUCT_ID = 'product_id',
  PRODUCT_NAME = 'product_name'
}
