import { CLUSTER_SETTING_MAIN_TYPE } from './cluster.setting.type.enum';

export enum CLUSTER_MEMBER_TYPE {
  /** 主力會員 */
  MAIN = 'main',
  /** 瞌睡會員 */
  DROWSY = 'drowsy',
  /** 沈睡會員 */
  SLEEPY = 'sleepy',
  /** 流失會員 */
  LOST = 'lost'
}

export const CLUSTER_MEMBER_SETTING_TYPE = {
  [CLUSTER_SETTING_MAIN_TYPE.MAIN_MEMBER]: CLUSTER_MEMBER_TYPE.MAIN,
  [CLUSTER_SETTING_MAIN_TYPE.DROWSY_MEMBER]: CLUSTER_MEMBER_TYPE.DROWSY,
  [CLUSTER_SETTING_MAIN_TYPE.SLEEPY_MEMBER]: CLUSTER_MEMBER_TYPE.SLEEPY,
  [CLUSTER_SETTING_MAIN_TYPE.LOST_MEMBER]: CLUSTER_MEMBER_TYPE.LOST
};
