export enum REPLACE_STRING {
  /** 品牌 */
  BRAND_NAME = '{=brandName=}',
  /** 集點卡集滿點數 */
  CARD_FULL_POINT = '{=cardFullPoint=}',
  /** 集點卡 */
  CARD_NAME = '{=cardName=}',
  /** 優惠券 */
  COUPON_NAME = '{=couponName=}',
  /** 目前集點卡累計點數 */
  CURRNET_CARD_POINT = '{=currentCardPoint=}',
  /** 會員累計積點 */
  MEMBER_POINT = '{=memberPoint=}',
  /** 會籍到期日 */
  MEMBER_SHIP_END_DATE = '{=memberShipEndDate=}',
  /** 會籍：會籍名稱 */
  MEMBER_SHIP_NAME = '{=memberShipName=}',
  /** 會籍起始日 */
  MEMBER_SHIP_START_DATE = '{=memberShipStartDate=}',
  /** 生日月份 */
  MONTH = '{=month=}',
  /** 積點到期日 */
  POINT_END_DATE = '{=pointEndDate=}',
  /** 兌換商品 */
  PRODUCT_NAME = '{=productName=}',
  /** 註冊日 */
  REGISTER_DATE = '{=registerDate=}',
  /** 註冊禮到期日 */
  REGISTER_GIFT_END_DATE = '{=registerGiftEndDate=}',
  /** 續等-差異金額 */
  RENEWAL_DIFF_AMOUNT = '{=renewalDiffAmount=}',
  /** 續等-差異消費次數 */
  RENEWAL_DIFF_COUNT = '{=renewalDiffCount=}',
  /** 兌換商品核銷分店 */
  STORE_NAME = '{=storeName=}',
  /** 目前累積消費金額 */
  TOTAL_AMOUNT = '{=totalAmount=}',
  /** 升等/續等-差異金額 */
  UPGRADE_GIFT_SEND_DIFF_AMOUNT = '{=upgradeGiftSendDiffAmount=}',
  /** 升等/續等-差異消費次數 */
  UPGRADE_GIFT_SEND_DIFF_COUNT = '{=upgradeGiftSendDiffCount=}'
}
